"""empty message

Revision ID: 34144842f155
Revises: 465f153f6816
Create Date: 2025-03-28 02:41:31.117907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34144842f155'
down_revision = '465f153f6816'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('admin_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('last_loggedin', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('admin_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('password')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['users_email'])
        batch_op.create_unique_constraint(None, ['users_phonenumber'])
        batch_op.create_unique_constraint(None, ['users_password'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')

    op.drop_table('admin')
    # ### end Alembic commands ###
