"""empty message

Revision ID: 465f153f6816
Revises: 
Create Date: 2025-03-28 02:37:24.622524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '465f153f6816'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artists',
    sa.Column('artist_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('artist_firstname', sa.String(length=100), nullable=False),
    sa.Column('artist_lastname', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('artist_id')
    )
    op.create_table('instruments',
    sa.Column('instru_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('instr_name', sa.String(length=100), nullable=False),
    sa.Column('instru_type', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('instru_id')
    )
    op.create_table('songs',
    sa.Column('songs_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('songs_title', sa.String(length=200), nullable=False),
    sa.Column('song_lyrics', sa.TEXT(), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('songs_id')
    )
    op.create_table('user',
    sa.Column('users_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('users_firstname', sa.String(length=100), nullable=False),
    sa.Column('users_lastname', sa.String(length=100), nullable=False),
    sa.Column('users_email', sa.String(length=150), nullable=False),
    sa.Column('users_phonenumber', sa.String(length=100), nullable=False),
    sa.Column('users_password', sa.String(length=45), nullable=False),
    sa.Column('users_profilepicture', sa.BLOB(), nullable=False),
    sa.Column('user_verified', sa.BLOB(), nullable=False),
    sa.Column('users_role', sa.Enum('user', 'scorers'), nullable=True),
    sa.Column('date_registered', sa.DateTime(), nullable=True),
    sa.Column('date_loggedin', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('users_id')
    )
    op.create_table('requests',
    sa.Column('requests_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('song_id', sa.Integer(), nullable=True),
    sa.Column('request_message', sa.TEXT(), nullable=False),
    sa.Column('date_requested', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['song_id'], ['songs.songs_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.users_id'], ),
    sa.PrimaryKeyConstraint('requests_id')
    )
    op.create_table('song_solfa',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('song_id', sa.Integer(), nullable=True),
    sa.Column('instrument_id', sa.Integer(), nullable=True),
    sa.Column('solfa_notation', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.instru_id'], ),
    sa.ForeignKeyConstraint(['song_id'], ['songs.songs_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('songs_artist',
    sa.Column('song_artist_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('song_id', sa.Integer(), nullable=True),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.artist_id'], ),
    sa.ForeignKeyConstraint(['song_id'], ['songs.songs_id'], ),
    sa.PrimaryKeyConstraint('song_artist_id')
    )
    op.create_table('user__instrument',
    sa.Column('user_instru_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('instrument_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.instru_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.users_id'], ),
    sa.PrimaryKeyConstraint('user_instru_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user__instrument')
    op.drop_table('songs_artist')
    op.drop_table('song_solfa')
    op.drop_table('requests')
    op.drop_table('user')
    op.drop_table('songs')
    op.drop_table('instruments')
    op.drop_table('artists')
    # ### end Alembic commands ###
