"""empty message

Revision ID: 81236d4dbcb5
Revises: 
Create Date: 2025-04-03 21:35:15.569903

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '81236d4dbcb5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('song_solfa', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'instruments', ['instrument_id'], ['instru_id'])
        batch_op.create_foreign_key(None, 'songs', ['song_id'], ['songs_id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'instruments', ['user_instru'], ['instru_id'])

    with op.batch_alter_table('user__instrument', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'instruments', ['instrument_id'], ['instru_id'])
        batch_op.drop_column('user_instru_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user__instrument', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_instru_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('song_solfa', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('instruments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))

    op.create_table('artistsongs',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('artist_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('song_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('tonic_solfa', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('artist_songs')
    # ### end Alembic commands ###
